// BACKPACK MUSIC

// TOWN
$SONG[DR3,LENGTH] = 102;
$SONG[ANFOR1,LENGTH] = 233;
$SONG[VILLAGE,LENGTH] = 158;
$SONG[EMOREJ1,LENGTH] = 203;
$SONG[KF5,LENGTH] = 74;
$SONG[ME2,LENGTH] = 104;
$SONG[ZIEGLER1,LENGTH] = 214;
$SONG[MACROF1,LENGTH] = 102;
$SONG[DS5,LENGTH] = 312;
$SONG[BLNGRD1,LENGTH] = 191;
$SONG[FIELDS,LENGTH] = 64;
$SONG[KeldrinTown,LENGTH] = 102;
$SONG[keldrinmusic2,LENGTH] = 54;
$SONG[MACROF2,LENGTH] = 127;
$SONG[BG4,LENGTH] = 103;
$SONG[DS7,LENGTH] = 102;
$SONG[CAP1,LENGTH] = 199;
$SONG[BG5,LENGTH] = 48;
$SONG[BG3,LENGTH] = 95;
$SONG[UO1,LENGTH] = 62;
$SONG[FF2,LENGTH] = 171;
$SONG[UO3,LENGTH] = 56;
$SONG[UO2,LENGTH] = 66;

// DUNGEON
$SONG[BG2,LENGTH] = 103;
$SONG[CRIM1,LENGTH] = 219;
$SONG[RIV4,LENGTH] = 137;
$SONG[KF3,LENGTH] = 91;
$SONG[CHAMBER1,LENGTH] = 158;
$SONG[DR1,LENGTH] = 95;
$SONG[RIV2,LENGTH] = 64;
$SONG[RIV1,LENGTH] = 60;
$SONG[AURICULAR2,LENGTH] = 211;
$SONG[AURICULAR1,LENGTH] = 200;
$SONG[RIV5,LENGTH] = 135;
$SONG[RIV6,LENGTH] = 134;
$SONG[BG7,LENGTH] = 86;
$SONG[DS2,LENGTH] = 176;
$SONG[DS1,LENGTH] = 176;
$SONG[BG1,LENGTH] = 57;
$SONG[ID3,LENGTH] = 67;
$SONG[ID1,LENGTH] = 64;
$SONG[RIV3,LENGTH] = 64;
$SONG[ID2,LENGTH] = 62;
$SONG[ID4,LENGTH] = 62;
$SONG[DR2,LENGTH] = 110;
$SONG[minemusic2,LENGTH] = 47;

//=========================================================================================================

$MUSICSET[DUNGEON,COUNT] = 23;
$MUSICSET[DUNGEON,1] = "BG2";
$MUSICSET[DUNGEON,2] = "CRIM1";
$MUSICSET[DUNGEON,3] = "RIV4";
$MUSICSET[DUNGEON,4] = "KF3";
$MUSICSET[DUNGEON,5] = "CHAMBER1";
$MUSICSET[DUNGEON,6] = "DR1";
$MUSICSET[DUNGEON,7] = "RIV2";
$MUSICSET[DUNGEON,8] = "RIV1";
$MUSICSET[DUNGEON,9] = "AURICULAR2";
$MUSICSET[DUNGEON,10] = "AURICULAR1";
$MUSICSET[DUNGEON,11] = "RIV5";
$MUSICSET[DUNGEON,12] = "RIV6";
$MUSICSET[DUNGEON,13] = "BG7";
$MUSICSET[DUNGEON,14] = "DS2";
$MUSICSET[DUNGEON,15] = "DS1";
$MUSICSET[DUNGEON,16] = "BG1";
$MUSICSET[DUNGEON,17] = "ID3";
$MUSICSET[DUNGEON,18] = "ID1";
$MUSICSET[DUNGEON,19] = "RIV3";
$MUSICSET[DUNGEON,20] = "ID2";
$MUSICSET[DUNGEON,21] = "ID4";
$MUSICSET[DUNGEON,22] = "DR2";
$MUSICSET[DUNGEON,23] = "minemusic2";

$MUSICSET[TOWN,COUNT] = 24;
$MUSICSET[TOWN,1] = "DR3";
$MUSICSET[TOWN,2] = "ANFOR1";
$MUSICSET[TOWN,3] = "VILLAGE";
$MUSICSET[TOWN,4] = "EMOREJ1";
$MUSICSET[TOWN,5] = "KF5";
$MUSICSET[TOWN,6] = "ME2";
$MUSICSET[TOWN,7] = "ZIEGLER1";
$MUSICSET[TOWN,8] = "MACROF1";
$MUSICSET[TOWN,9] = "DS5";
$MUSICSET[TOWN,10] = "BLNGRD1";
$MUSICSET[TOWN,11] = "FIELDS";
$MUSICSET[TOWN,12] = "KeldrinTown";
$MUSICSET[TOWN,13] = "keldrinmusic2";
$MUSICSET[TOWN,14] = "MACROF2";
$MUSICSET[TOWN,16] = "BG4";
$MUSICSET[TOWN,17] = "DS7";
$MUSICSET[TOWN,18] = "CAP1";
$MUSICSET[TOWN,19] = "BG5";
$MUSICSET[TOWN,20] = "BG3";
$MUSICSET[TOWN,21] = "UO1";
$MUSICSET[TOWN,22] = "FF2";
$MUSICSET[TOWN,23] = "UO3";
$MUSICSET[TOWN,24] = "UO2";

//=========================================================================================================

// KELDRIN
$ZONEMUSIC[KTOWN] = "TOWN";
$ZONEMUSIC[OLDCELLAR] = "DUNGEON";
$ZONEMUSIC[FORGOTTENMINE] = "DUNGEON";
$ZONEMUSIC[CULTISTHIDEOUT] = "DUNGEON";
$ZONEMUSIC[OLDKELDRIN] = "DUNGEON";
$ZONEMUSIC[UNDERTOWER] = "DUNGEON";
$ZONEMUSIC[UNDERPATH] = "DUNGEON";
$ZONEMUSIC[CATACOMBS] = "DUNGEON";
$ZONEMUSIC[STRONGHOLD] = "TOWN";
$ZONEMUSIC[CAMP] = "TOWN";
$ZONEMUSIC[TOWER] = "TOWN";

// RAKHAR
$ZONEMUSIC[DESTOWN] = "TOWN";
$ZONEMUSIC[SEWERS] = "DUNGEON";
$ZONEMUSIC[OASIS] = "DUNGEON";
$ZONEMUSIC[DUSTYCAVE] = "DUNGEON";
$ZONEMUSIC[TEMPLE] = "DUNGEON";
$ZONEMUSIC[LIBRARY] = "DUNGEON";
$ZONEMUSIC[SUNPYRAMID] = "DUNGEON";

// GUL'WAR
$ZONEMUSIC[JTOWN] = "TOWN";
$ZONEMUSIC[UNDERWELL] = "DUNGEON";
$ZONEMUSIC[FLOODCAV] = "DUNGEON";
$ZONEMUSIC[WATERWAY] = "DUNGEON";
$ZONEMUSIC[UNDERTREE] = "DUNGEON";
$ZONEMUSIC[EMERALD] = "DUNGEON";
$ZONEMUSIC[DARK] = "DUNGEON";

$ZONEMUSIC["FOREST1"] = "DUNGEON";
$ZONEMUSIC["FOREST2"] = "DUNGEON";
$ZONEMUSIC["FOREST3"] = "DUNGEON";
$ZONEMUSIC["FOREST4"] = "DUNGEON";
$ZONEMUSIC["DESERT1"] = "DUNGEON";
$ZONEMUSIC["DESERT2"] = "DUNGEON";
$ZONEMUSIC["DESERT3"] = "DUNGEON";
$ZONEMUSIC["DESERT4"] = "DUNGEON";
$ZONEMUSIC["JUNGLE1"] = "DUNGEON";
$ZONEMUSIC["JUNGLE2"] = "DUNGEON";
$ZONEMUSIC["JUNGLE3"] = "DUNGEON";
$ZONEMUSIC["JUNGLE4"] = "DUNGEON";
$ZONEMUSIC["FROZEN1"] = "DUNGEON";
$ZONEMUSIC["FROZEN2"] = "DUNGEON";
$ZONEMUSIC["FROZEN3"] = "DUNGEON";
$ZONEMUSIC["FROZEN4"] = "DUNGEON";
$ZONEMUSIC["FROZEN5"] = "DUNGEON";
$ZONEMUSIC["LAVA1"] = "DUNGEON";
$ZONEMUSIC["LAVA2"] = "DUNGEON";
$ZONEMUSIC["LAVA3"] = "DUNGEON";
$ZONEMUSIC["LAVA4"] = "DUNGEON";
$ZONEMUSIC["LAVA5"] = "DUNGEON";
$ZONEMUSIC["ARCANE1"] = "DUNGEON";
$ZONEMUSIC["ARCANE2"] = "DUNGEON";
$ZONEMUSIC["ARCANE3"] = "DUNGEON";
$ZONEMUSIC["ARCANE4"] = "DUNGEON";
$ZONEMUSIC["ARCANE5"] = "DUNGEON";
$ZONEMUSIC["HELL1"] = "DUNGEON";
$ZONEMUSIC["HELL2"] = "DUNGEON";
$ZONEMUSIC["HELL3"] = "DUNGEON";
$ZONEMUSIC["HELL4"] = "DUNGEON";
$ZONEMUSIC["HELL5"] = "DUNGEON";

//=========================================================================================================

function PlayCrucibleMusic(%id)
{
	%zone = fetchData(%id,"ZONE");
	if (%zone == "UNKNOWN") {
		if ($CURRENTCRUMAP == "JUNGLE") {
			Client::SendMessage(%id,0,"~wjungle_ambient.wav");
			%l = 187;
			%add = MTRB(10,20);
			$MUSICTICKER[%id] = %l + %add;
		}
	}
	else {
		%music = $ZONEMUSIC[%zone];
		if (%music == "") return;
		%count = $MUSICSET[%music,COUNT];
		%do = MTRB(1,%count);
		%song = $MUSICSET[%music,%do];
		%l = $SONG[%song,LENGTH];
		Client::SendMessage(%id,0,"~w" @ %song @ ".wav");
		%add = MTRB(60,180);
		$MUSICTICKER[%id] = %l + %add;
	}
}



echo("__MUSIC LOADED");