MissionRegObject( RPG, "Crystal", MissionCreateObject, Crystal, StaticShape, Crystal );
MissionRegObject( RPG, "Empty Crystal", MissionCreateObject, EmptyCrystal, StaticShape, EmptyCrystal );
MissionRegObject( RPG, "SoundPoint", MissionCreateObject, SoundPoint, StaticShape, SoundPoint );

MissionRegObject( Platforms, "Ferry Platform", MissionCreateObject, PlatformFerry,  Moveable, PlatformFerry );

// ADDED CRUCIBLE
MissionRegObject(CRUCIBLE, "PINE", MissionCreateObject, PINE, StaticShape, PINE );
MissionRegObject(CRUCIBLE, "PINEMED", MissionCreateObject, PINEMED, StaticShape, PINEMED );
MissionRegObject(CRUCIBLE, "CRUWATER1", MissionCreateObject, CRUWATER1, StaticShape, CRUWATER1 );
MissionRegObject(CRUCIBLE, "CPITFIRE", MissionCreateObject, CPITFIRE, StaticShape, CPITFIRE );
MissionRegObject(CRUCIBLE, "ROUGEFLAG", MissionCreateObject, ROUGEFLAG, StaticShape, ROUGEFLAG );
MissionRegObject(CRUCIBLE, "CPORTAL1", MissionCreateObject, CPORTAL1, StaticShape, CPORTAL1 );
MissionRegObject(CRUCIBLE, "CROCK1", MissionCreateObject, CROCK1, StaticShape, CROCK1 );
MissionRegObject(CRUCIBLE, "CROCK2", MissionCreateObject, CROCK2, StaticShape, CROCK2 );
MissionRegObject(CRUCIBLE, "SHRUB1", MissionCreateObject, SHRUB1, StaticShape, SHRUB1 );
MissionRegObject(CRUCIBLE, "ORANGEGLOW", MissionCreateObject, ORANGEGLOW, StaticShape, ORANGEGLOW );
MissionRegObject(CRUCIBLE, "BLUEGLOW", MissionCreateObject, BLUEGLOW, StaticShape, BLUEGLOW );
MissionRegObject(CRUCIBLE, "IRONGATE", MissionCreateObject, IRONGATE, StaticShape, IRONGATE );
MissionRegObject(CRUCIBLE, "WARP", MissionCreateObject, WARP, StaticShape, WARP );
MissionRegObject(CRUCIBLE, "SBEAM1", MissionCreateObject, SBEAM1, StaticShape, SBEAM1 );
MissionRegObject(CRUCIBLE, "DFOUNTAIN1", MissionCreateObject, DFOUNTAIN1, StaticShape, DFOUNTAIN1 );
MissionRegObject(CRUCIBLE, "DFOUNTAIN2", MissionCreateObject, DFOUNTAIN2, StaticShape, DFOUNTAIN2 );
MissionRegObject(CRUCIBLE, "LAVA1", MissionCreateObject, LAVA1, StaticShape, LAVA1 );
MissionRegObject(CRUCIBLE, "ROOT1", MissionCreateObject, ROOT1, StaticShape, ROOT1 );
MissionRegObject(CRUCIBLE, "OAKLARGE", MissionCreateObject, OAKLARGE, StaticShape, OAKLARGE );
MissionRegObject(CRUCIBLE, "MUCKWATER1", MissionCreateObject, MUCKWATER1, StaticShape, MUCKWATER1 );
MissionRegObject(CRUCIBLE, "LAVA2", MissionCreateObject, LAVA2, StaticShape, LAVA2 );
MissionRegObject(CRUCIBLE, "LAVA3", MissionCreateObject, LAVA3, StaticShape, LAVA3 );
MissionRegObject(CRUCIBLE, "CHAIN1", MissionCreateObject, CHAIN1, StaticShape, CHAIN1 );
MissionRegObject(CRUCIBLE, "PHA_PORTAL", MissionCreateObject, PHA_PORTAL, StaticShape, PHA_PORTAL );
MissionRegObject(CRUCIBLE, "fire_small", MissionCreateObject, fire_small, StaticShape, fire_small );
MissionRegObject(CRUCIBLE, "fire_medium", MissionCreateObject, fire_medium, StaticShape, fire_medium );
MissionRegObject(CRUCIBLE, "fire_large", MissionCreateObject, fire_large, StaticShape, fire_large );
MissionRegObject(CRUCIBLE, "fire_omg", MissionCreateObject, fire_omg, StaticShape, fire_omg );
MissionRegObject(CRUCIBLE, "JUNGLEPLANT2", MissionCreateObject, JUNGLEPLANT2, StaticShape, JUNGLEPLANT2 );
MissionRegObject(CRUCIBLE, "JUNGLEPLANT2_S", MissionCreateObject, JUNGLEPLANT2_S, StaticShape, JUNGLEPLANT2_S );
MissionRegObject(CRUCIBLE, "FERN", MissionCreateObject, FERN, StaticShape, FERN );
MissionRegObject(CRUCIBLE, "FERN_M", MissionCreateObject, FERN_M, StaticShape, FERN_M );
MissionRegObject(CRUCIBLE, "JTREE_B", MissionCreateObject, JTREE_B, StaticShape, JTREE_B );
MissionRegObject(CRUCIBLE, "JTREE_M", MissionCreateObject, JTREE_M, StaticShape, JTREE_M );
MissionRegObject(CRUCIBLE, "JTREE_S", MissionCreateObject, JTREE_S, StaticShape, JTREE_S );
MissionRegObject(CRUCIBLE, "JBUSH_B", MissionCreateObject, JBUSH_B, StaticShape, JBUSH_B );
MissionRegObject(CRUCIBLE, "JBUSH_M", MissionCreateObject, JBUSH_M, StaticShape, JBUSH_M );
MissionRegObject(CRUCIBLE, "JBUSH_S", MissionCreateObject, JBUSH_S, StaticShape, JBUSH_S );
MissionRegObject(CRUCIBLE, "JPALM_BIG", MissionCreateObject, JPALM_BIG, StaticShape, JPALM_BIG );
MissionRegObject(CRUCIBLE, "JPALM_M", MissionCreateObject, JPALM_M, StaticShape, JPALM_M );
MissionRegObject(CRUCIBLE, "JPALM_S", MissionCreateObject, JPALM_S, StaticShape, JPALM_S );
MissionRegObject(CRUCIBLE, "JOCEAN", MissionCreateObject, JOCEAN, StaticShape, JOCEAN );
MissionRegObject(CRUCIBLE, "JRIVER", MissionCreateObject, JRIVER, StaticShape, JRIVER );
MissionRegObject(CRUCIBLE, "GRASS_B", MissionCreateObject, GRASS_B, StaticShape, GRASS_B );
MissionRegObject(CRUCIBLE, "GRASS_M", MissionCreateObject, GRASS_M, StaticShape, GRASS_M );
MissionRegObject(CRUCIBLE, "GRASS_S", MissionCreateObject, GRASS_S, StaticShape, GRASS_S );
MissionRegObject(CRUCIBLE, "BLUE_RAY", MissionCreateObject, BLUE_RAY, StaticShape, BLUE_RAY );
MissionRegObject(CRUCIBLE, "CAVE_WATER", MissionCreateObject, CAVE_WATER, StaticShape, CAVE_WATER );
MissionRegObject(CRUCIBLE, "TEMPLE_WATER", MissionCreateObject, TEMPLE_WATER, StaticShape, TEMPLE_WATER );
MissionRegObject(CRUCIBLE, "LAVARIVER1", MissionCreateObject, LAVARIVER1, StaticShape, LAVARIVER1 );
MissionRegObject(CRUCIBLE, "LAVARIVER2", MissionCreateObject, LAVARIVER2, StaticShape, LAVARIVER2 );
MissionRegObject(CRUCIBLE, "INVISWALL_1", MissionCreateObject, INVISWALL_1, StaticShape, INVISWALL_1 );
MissionRegObject(CRUCIBLE, "INVISWALL_2", MissionCreateObject, INVISWALL_2, StaticShape, INVISWALL_2 );
MissionRegObject(CRUCIBLE, "CRUBIGWALL", MissionCreateObject, CRUBIGWALL, StaticShape, CRUBIGWALL );
MissionRegObject(CRUCIBLE, "CRUBIGGERWALL", MissionCreateObject, CRUBIGGERWALL, StaticShape, CRUBIGGERWALL );
MissionRegObject(CRUCIBLE, "CRUHUGEWALL", MissionCreateObject, CRUHUGEWALL, StaticShape, CRUHUGEWALL );
MissionRegObject(CRUCIBLE, "DBUSH_SMALL", MissionCreateObject, DBUSH_SMALL, StaticShape, DBUSH_SMALL );
MissionRegObject(CRUCIBLE, "DBUSH_MED", MissionCreateObject, DBUSH_MED, StaticShape, DBUSH_MED );
MissionRegObject(CRUCIBLE, "DTREE_S", MissionCreateObject, DTREE_S, StaticShape, DTREE_S );
MissionRegObject(CRUCIBLE, "DTREE2_S", MissionCreateObject, DTREE2_S, StaticShape, DTREE2_S );
MissionRegObject(CRUCIBLE, "DTREE3_S", MissionCreateObject, DTREE3_S, StaticShape, DTREE3_S );
MissionRegObject(CRUCIBLE, "FLAKE", MissionCreateObject, FLAKE, StaticShape, FLAKE );
MissionRegObject(CRUCIBLEFOREST, "FTREE1_L", MissionCreateObject, FTREE1_L, StaticShape, FTREE1_L );
MissionRegObject(CRUCIBLEFOREST, "FTREE1_M", MissionCreateObject, FTREE1_M, StaticShape, FTREE1_M );
MissionRegObject(CRUCIBLEFOREST, "FTREE1_S", MissionCreateObject, FTREE1_S, StaticShape, FTREE1_S );
MissionRegObject(CRUCIBLEFOREST, "FTREE2_L", MissionCreateObject, FTREE2_L, StaticShape, FTREE2_L );
MissionRegObject(CRUCIBLEFOREST, "FTREE2_M", MissionCreateObject, FTREE2_M, StaticShape, FTREE2_M );
MissionRegObject(CRUCIBLEFOREST, "FTREE2_S", MissionCreateObject, FTREE2_S, StaticShape, FTREE2_S );
MissionRegObject(CRUCIBLEFOREST, "FTREE3_L", MissionCreateObject, FTREE3_L, StaticShape, FTREE3_L );
MissionRegObject(CRUCIBLEFOREST, "FTREE3_M", MissionCreateObject, FTREE3_M, StaticShape, FTREE3_M );
MissionRegObject(CRUCIBLEFOREST, "FTREE3_S", MissionCreateObject, FTREE3_S, StaticShape, FTREE3_S );
MissionRegObject(CRUCIBLEFOREST, "FTREE4_L", MissionCreateObject, FTREE4_L, StaticShape, FTREE4_L );
MissionRegObject(CRUCIBLEFOREST, "FTREE4_M", MissionCreateObject, FTREE4_M, StaticShape, FTREE4_M );
MissionRegObject(CRUCIBLEFOREST, "FTREE4_S", MissionCreateObject, FTREE4_S, StaticShape, FTREE4_S );
MissionRegObject(CRUCIBLEFOREST, "FBUSH1_S", MissionCreateObject, FBUSH1_S, StaticShape, FBUSH1_S );
MissionRegObject(CRUCIBLEFOREST, "FBUSH1_M", MissionCreateObject, FBUSH1_M, StaticShape, FBUSH1_M );
MissionRegObject(CRUCIBLEFOREST, "FBUSH2_S", MissionCreateObject, FBUSH2_S, StaticShape, FBUSH2_S );
MissionRegObject(CRUCIBLEFOREST, "FBUSH2_M", MissionCreateObject, FBUSH2_M, StaticShape, FBUSH2_M );
MissionRegObject(CRUCIBLEFOREST, "FROCK1_S", MissionCreateObject, FROCK1_S, StaticShape, FROCK1_S );
MissionRegObject(CRUCIBLEFOREST, "FROCK1_M", MissionCreateObject, FROCK1_M, StaticShape, FROCK1_M );
MissionRegObject(CRUCIBLEFOREST, "FROCK1_L", MissionCreateObject, FROCK1_L, StaticShape, FROCK1_L );
MissionRegObject(CRUCIBLE, "WINDOW3X3", MissionCreateObject, WINDOW3X3, StaticShape, WINDOW3X3 );
MissionRegObject(CRUCIBLE, "WINDOW3X4", MissionCreateObject, WINDOW3X4, StaticShape, WINDOW3X4 );
MissionRegObject(CRUCIBLE, "CRYSTALBALL", MissionCreateObject, CRYSTALBALL, StaticShape, CRYSTALBALL );
MissionRegObject(CRUCIBLE, "PURPBEAM", MissionCreateObject, PURPBEAM, StaticShape, PURPBEAM );
MissionRegObject(CRUCIBLE, "ROGUECAMP", MissionCreateObject, ROGUECAMP, StaticShape, ROGUECAMP );
MissionRegObject(CRUCIBLE, "TREASURE3", MissionCreateObject, TREASURE3, StaticShape, TREASURE3 );
MissionRegObject(CRUCIBLE, "SMOKE_FRAME", MissionCreateObject, SMOKE_FRAME, StaticShape, SMOKE_FRAME );
MissionRegObject(CRUCIBLE, "SWORDWINDOW", MissionCreateObject, SWORDWINDOW, StaticShape, SWORDWINDOW );
MissionRegObject(CRUCIBLE, "CRU_CRYSTAL_S", MissionCreateObject, CRU_CRYSTAL_S, StaticShape, CRU_CRYSTAL_S );
MissionRegObject(CRUCIBLE, "CULTIST", MissionCreateObject, CULTIST, StaticShape, CULTIST );
MissionRegObject(CRUCIBLE, "CULTIST_CANDLE", MissionCreateObject, CULTIST_CANDLE, StaticShape, CULTIST_CANDLE );
MissionRegObject(CRUCIBLE, "CRU_PORTAL3", MissionCreateObject, CRU_PORTAL3, StaticShape, CRU_PORTAL3 );
MissionRegObject(CRUCIBLE, "MAPPORTAL", MissionCreateObject, MAPPORTAL, StaticShape, MAPPORTAL );
MissionRegObject(CRUCIBLE, "SPIKEGATE", MissionCreateObject, SPIKEGATE, StaticShape, SPIKEGATE );

MissionRegObject(CRUCIBLESNOW, "STREE_S", MissionCreateObject, STREE_S, StaticShape, STREE_S );

missionRegDis(CRUCIBLE,dock1);
missionRegDis(CRUCIBLE,kefence1);
missionRegDis(CRUCIBLE,ketower1);
missionRegDis(CRUCIBLE,stnwall1);
missionRegDis(CRUCIBLE,cruhut2);
missionRegDis(CRUCIBLE,cfirepit1);
missionRegDis(CRUCIBLE,cavent1);
missionRegDis(CRUCIBLE,ccavern1);
missionRegDis(CRUCIBLE,wartower1);
missionRegDis(CRUCIBLE,cruportal1);
missionRegDis(CRUCIBLE,cruwhouse1);
missionRegDis(CRUCIBLE,crubank1);
missionRegDis(CRUCIBLE,brickwalk1);
missionRegDis(CRUCIBLE,kelamppost1);
missionRegDis(CRUCIBLE,kemarket);
missionRegDis(CRUCIBLE,forest_land_1);
missionRegDis(CRUCIBLE,forest_island_1);
missionRegDis(CRUCIBLE,warproom1);
missionRegDis(CRUCIBLE,ter_kwoods);
missionRegDis(CRUCIBLE,ter_kvalley);
missionRegDis(CRUCIBLE,kmountain1);
missionRegDis(CRUCIBLE,kmountain4);
missionRegDis(CRUCIBLE,crurock1);
missionRegDis(CRUCIBLE,kbridge1);
missionRegDis(CRUCIBLE,ter_kmountain2);
missionRegDis(CRUCIBLE,ccastle1);
missionRegDis(CRUCIBLE,cc1);
missionRegDis(CRUCIBLE,hkeep1);
missionRegDis(CRUCIBLE,crudest2);
missionRegDis(CRUCIBLE,cruhse4);
missionRegDis(CRUCIBLE,cruhsed5);
missionRegDis(CRUCIBLE,cdeswall1);
missionRegDis(CRUCIBLE,cdeswall2);
missionRegDis(CRUCIBLE,crhsed3);
missionRegDis(CRUCIBLE,ter_mountain3);
missionRegDis(CRUCIBLE,ter_gvill);
missionRegDis(CRUCIBLE,totd1);
missionRegDis(CRUCIBLE,desert2);
missionRegDis(CRUCIBLE,des_tower);
missionRegDis(CRUCIBLE,hpain1);
missionRegDis(CRUCIBLE,cellar1);
missionRegDis(CRUCIBLE,undertower1);
missionRegDis(CRUCIBLE,ter_forest2);
missionRegDis(CRUCIBLE,ter_forest3);
missionRegDis(CRUCIBLE,forestbridge1);
missionRegDis(CRUCIBLE,underpath);
missionRegDis(CRUCIBLE,fwaterway);
missionRegDis(CRUCIBLE,pit1);
missionRegDis(CRUCIBLE,desswe1);
missionRegDis(CRUCIBLE,volcano1);
missionRegDis(CRUCIBLE,volcano_mid);
missionRegDis(CRUCIBLE,vcastle);
missionRegDis(CRUCIBLE,icecavern1);
missionRegDis(CRUCIBLE,rodm_2);
missionRegDis(CRUCIBLE,ter_desert3);
missionRegDis(CRUCIBLE,limbo2);
missionRegDis(CRUCIBLE,town_jungle);
missionRegDis(CRUCIBLE,town_jmarket);
missionRegDis(CRUCIBLE,jungle1);
missionRegDis(CRUCIBLE,jungle2);
missionRegDis(CRUCIBLE,losttemple);
missionRegDis(CRUCIBLE,losttemple2);
missionRegDis(CRUCIBLE,losttemple3);
missionRegDis(CRUCIBLE,jungleriver);
missionRegDis(CRUCIBLE,junglebridge);
missionRegDis(CRUCIBLE,tribalflood);
missionRegDis(CRUCIBLE,jungle3);
missionRegDis(CRUCIBLE,jungleriver2);
missionRegDis(CRUCIBLE,tribalbridge2);
missionRegDis(CRUCIBLE,emeraldmine);
missionRegDis(CRUCIBLE,underwell);
missionRegDis(CRUCIBLE,fjail2);
missionRegDis(CRUCIBLE,hpint);
missionRegDis(CRUCIBLE,floodcav);
missionRegDis(CRUCIBLE,catacomb1);
missionRegDis(CRUCIBLE,undertree);
missionRegDis(CRUCIBLE,templeruins);
missionRegDis(CRUCIBLE,fire1);
missionRegDis(CRUCIBLE,firebridge);
missionRegDis(CRUCIBLE,pit2);
missionRegDis(CRUCIBLE,cellar_ent);
missionRegDis(CRUCIBLE,caveent2);
missionRegDis(CRUCIBLE,towerent1);
missionRegDis(CRUCIBLE,oasisruins1);
missionRegDis(CRUCIBLE,oruinsent);
missionRegDis(CRUCIBLE,bigdesrock1);
missionRegDis(CRUCIBLE,sunpyramid);
missionRegDis(CRUCIBLE,dustycave);
missionRegDis(CRUCIBLE,cubes_1);
missionRegDis(CRUCIBLE,cubes_arcane);
missionRegDis(CRUCIBLE,cube_jungle1);
missionRegDis(CRUCIBLE,cube_frozen2);
missionRegDis(CRUCIBLE,cube_frozen3);
missionRegDis(CRUCIBLE,wbarracks);
missionRegDis(CRUCIBLE,m_magetower);
missionRegDis(CRUCIBLE,m_rogueruin);
missionRegDis(CRUCIBLE,cmagetower);
missionRegDis(CRUCIBLE,cmagetower_int);

missionRegDis(MAPS,cubes_1);
missionRegDis(MAPS,cube_forest1);
missionRegDis(MAPS,cube_forest2);
missionRegDis(MAPS,cube_desert1);
missionRegDis(MAPS,cube_desert2);
missionRegDis(MAPS,cube_desert4_2);
missionRegDis(MAPS,cube_jungle1);
missionRegDis(MAPS,cube_jungle2);
missionRegDis(MAPS,cube_jungle3);
missionRegDis(MAPS,cube_jungle4);
missionRegDis(MAPS,cube_frozen1);
missionRegDis(MAPS,cube_frozen2);
missionRegDis(MAPS,cube_frozen3);
missionRegDis(MAPS,cube_frozen4);
missionRegDis(MAPS,cube_lava1);
missionRegDis(MAPS,cube_lava2);
missionRegDis(MAPS,cube_lava3);
missionRegDis(MAPS,cube_lava4);
missionRegDis(MAPS,cube_lava5);
missionRegDis(MAPS,cube_arcane1);
missionRegDis(MAPS,cube_arcane2);
missionRegDis(MAPS,cube_arcane3);
missionRegDis(MAPS,cube_arcane4);
missionRegDis(MAPS,cube_arcane5);
missionRegDis(MAPS,cube_hell1);
missionRegDis(MAPS,cube_hell2);
missionRegDis(MAPS,cube_hell3);
missionRegDis(MAPS,cube_hell4);
missionRegDis(MAPS,cube_hell5);

MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN_L", MissionCreateObject, PHA_PUMPKIN_L, StaticShape, PHA_PUMPKIN_L);
MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN_M", MissionCreateObject, PHA_PUMPKIN_M, StaticShape, PHA_PUMPKIN_M);
MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN_S", MissionCreateObject, PHA_PUMPKIN_S, StaticShape, PHA_PUMPKIN_S);
MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN2_S", MissionCreateObject, PHA_PUMPKIN2_S, StaticShape, PHA_PUMPKIN2_S);
MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN2_M", MissionCreateObject, PHA_PUMPKIN2_M, StaticShape, PHA_PUMPKIN2_M);
MissionRegObject(PHANTOMSERVER, "PHA_PUMPKIN2_L", MissionCreateObject, PHA_PUMPKIN2_L, StaticShape, PHA_PUMPKIN2_L);
